version: "3"

services:
  previewer_service:
    build:
      context: ../
      dockerfile: ./build/Dockerfile-previewer
    image: previewer_service_docker_image    
    volumes:
      - ../configs/config-docker.toml:/etc/previewer/config.toml:ro

    restart: on-failure
    ports:
      - "8088:8088"  
    expose:
      - 8088

  web:
    build:
      context: ../
      dockerfile: ./build/Dockerfile-nginx   
    ports:
      - "8080:80"
    expose:
      - 80
    environment:      
      - NGINX_PORT=80

  integration_tests:
    build:
      context: ../
      dockerfile: ./build/Dockerfile-tests  
    command: "true" 
    links:
      - previewer_service
    restart: on-failure